alias apg='sudo apachectl graceful'
alias apr='sudo service httpd restart'
alias clog='date=`date "+%Y-%m-%d"`; tail -f /var/log/datashare/cocoon.log.$date'
alias datashare='sudo su - datashare'
alias dlog='date=`date "+%Y-%m-%d"`; tail -f /var/log/datashare/dspace.log.$date'
alias gitsmpull='git pull && git submodule update'
alias h='history'
alias psqldlocal='psql -d datashar -U datashar'
alias psqldvorlich='psql -d datashar -U datashar -p 6000 -h vorlichdb.edina.ac.uk'
alias rt='sudo su tomcat /usr/local/datashare/bin/service.sh restart_tomcat'
alias st='sudo /usr/local/datashare/bin/service.sh stop_tomcat'
alias tlog='tail -f /opt/tomcat/logs/catalina.out'

